# Git configuration, generated by home-manager into ~/.config/git/config.
#
# Unlike the shell and nvim configs (see links.nix) this one is not a symlink
# to the checkout: it is a flat key/value file that is edited about once a
# year, and generating it lets the two program paths below be store paths
# rather than a bet on PATH ordering.
#
# git reads ~/.gitconfig *instead of* the XDG path when it exists, so a box
# carrying a stray ~/.gitconfig silently shadows every setting here. Move it
# aside before the first switch.
{ pkgs, ... }:

{
  programs.git = {
    enable = true;

    # Emits the [filter "lfs"] block and pulls in git-lfs.
    lfs.enable = true;

    settings = {
      user = {
        name = "Tiberiu Voicu";
        email = "ts.voicu@icloud.com";
      };

      init.defaultBranch = "master";

      core = {
        autocrlf = false;
        # Absent on this box; harmless when missing, and still wanted on the
        # machines that do have one.
        excludesfile = "~/.gitignore_global";
        # less is left bare on purpose -- it is a system tool, not part of
        # this package set, so there is no store path to point at.
        pager = "${pkgs.diff-so-fancy}/bin/diff-so-fancy | less --tabs=4 -RFX";
      };

      # commit.gpgsign is deliberately absent. The old .gitconfig set it, but
      # that file was linked into no home directory, so signing has never
      # actually been on -- and switching it on breaks `git commit` outright on
      # any box without a secret key, this workspace included. Turn it on per
      # machine, or here once every machine has a key.
      # gpg-agent's pinentry is configured per-OS in install_scripts; only the
      # binary is pinned here.
      gpg.program = "${pkgs.gnupg}/bin/gpg";

      color = {
        ui = true;
        "diff-highlight" = {
          oldNormal = "red bold";
          oldHighlight = "red bold 52";
          newNormal = "green bold";
          newHighlight = "green bold 22";
        };
        diff = {
          meta = 11;
          frag = "magenta bold";
          commit = "yellow bold";
          old = "red bold";
          new = "green bold";
          whitespace = "red reverse";
        };
      };

      pull.rebase = false;
      branch.autosetuprebase = "never";
    };
  };
}
