return {
    { "nvim-treesitter/nvim-treesitter-textobjects", branch = "main" },
    {
        "nvim-treesitter/nvim-treesitter",
        lazy = false,
        build = ":TSUpdate",
        branch = "main",
        opts = {
            -- Modules and its options go here
            highlight = { enable = true },
            incremental_selection = { enable = true },
            indent = { enable = false },
            refactor = { smart_rename = { enable = true }, navigation = { enable = true } },
            textobjects = { enable = true },
            install_dir = vim.fn.stdpath("data") .. "/site",
        },
        config = function(_, opts)
            local parsers = {
                "bash",
                "c",
                "cpp",
                "css",
                "diff",
                "dockerfile",
                "git_rebase",
                "gitcommit",
                "go",
                "hcl",
                "html",
                "java",
                "javascript",
                "jsdoc",
                "json",
                "lua",
                "make",
                "python",
                "ruby",
                "rust",
                "scala",
                "sql",
                "ssh_config",
                "svelte",
                "terraform",
                "toml",
                "tsx",
                "typescript",
                "yaml",
                "zsh",
            }
            require("nvim-treesitter").install(parsers)
        end,
    },
}
